version: '2'
services:
  web:
    build: .
#    command: bash -c "python run.py"
    command: bash -c "sleep 100000"
    ports:
        - '8080:8080'
    volumes:
      - .:/code
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      POSTGRES_PASSWORD: jf984HWFj
    depends_on:
      - postgres

  postgres:
    environment:
      POSTGRES_PASSWORD: jf984HWFj
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 1m

volumes:
    db_data: