version: '2'
services:
  web:
    build: .
    command: bash -c "flask run --host=0.0.0.0"
    ports:
        - '5000:5000'
    volumes:
      - .:/code
#      - media:/code/media/
    environment:
      FLASK_APP: hangman
      FLASK_ENV: development
#    depends_on:
#      - postgres
